listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/

# Bridge para Solar Assistant
connection solar_assistant_bridge
address 192.168.50.211:1883
topic solar_assistant/# in 0
topic solar_assistant/# out 0
bridge_protocol_version mqttv311
restart_timeout 5
